# Main script

name: Hibiki

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Dependabot auto merge
      uses: ridedott/dependabot-auto-merge-action@v1.0.5
      with:
        GITHUB-TOKEN: "${{ secrets.GITHUB_TOKEN }}" 
    - name: Install, build, and test
      run: |
        echo Installing deps...
        npm install
        echo Finished installing all deps...
        echo Testing and building...
        npm run build --if-present
        npm test
        echo Finished!
      env:
        CI: true
